export { Home } from './home'
export { ONGDetail } from './ong-detail'
export { DonationPage } from './donation-page'
export { DonationsList } from './donations-list'
export { RegisterPage } from './register'
